import type { Wine, Action, DashboardStats, ProvenanceEvent } from "@/types/dual";
import { v4 as uuidv4 } from "uuid";

function makeProvenance(wineId: string, vintage: number): ProvenanceEvent[] {
  return [
    {
      id: uuidv4(),
      timestamp: `${vintage}-09-15T08:00:00Z`,
      type: "HARVEST",
      description: "Grapes harvested from estate vineyard",
      actor: "Estate Vineyard Team",
      location: "Estate Vineyard",
      verified: true,
    },
    {
      id: uuidv4(),
      timestamp: `${vintage}-10-01T10:00:00Z`,
      type: "VINIFICATION",
      description: "Fermentation and pressing completed",
      actor: "Head Winemaker",
      location: "Estate Winery",
      verified: true,
    },
    {
      id: uuidv4(),
      timestamp: `${vintage + 1}-06-15T10:00:00Z`,
      type: "BARREL_AGING",
      description: "Transferred to French oak barrels for aging",
      actor: "Cellar Master",
      location: "Barrel Room",
      verified: true,
    },
    {
      id: uuidv4(),
      timestamp: `${vintage + 2}-03-01T10:00:00Z`,
      type: "BOTTLING",
      description: "Bottled and corked at estate",
      actor: "Bottling Line",
      location: "Estate Bottling Facility",
      verified: true,
    },
    {
      id: uuidv4(),
      timestamp: "2024-01-10T10:00:00Z",
      type: "TOKENIZED",
      description: "Wine tokenized on DUAL network",
      actor: "DUAL Protocol",
      verified: true,
      txHash: "0x" + Array.from({ length: 64 }, () => Math.floor(Math.random() * 16).toString(16)).join(""),
    },
  ];
}

export const DEMO_WINES: Wine[] = [
  {
    id: "wine-001",
    status: "anchored",
    ownerId: "user-001",
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-06-15T10:00:00Z",
    anchoredAt: "2024-01-10T10:05:00Z",
    blockchainTxHash: "0xabc123def456",
    faces: [],
    provenance: [],
    wineData: {
      name: "Château Margaux 2015",
      producer: "Château Margaux",
      region: "Margaux, Bordeaux",
      country: "France",
      vintage: 2015,
      varietal: "Cabernet Sauvignon Blend",
      type: "red",
      abv: 13.5,
      volume: "750ml",
      quantity: 6,
      condition: "pristine",
      storage: "professional",
      drinkingWindow: { from: 2025, to: 2060 },
      ratings: [
        { critic: "Robert Parker", score: 99, year: 2018 },
        { critic: "Jancis Robinson", score: 19, year: 2018 },
      ],
      certifications: ["AOC Margaux", "Premier Grand Cru Classé"],
      currentValue: 4800,
      purchasePrice: 3200,
      description: "An extraordinary expression of Margaux terroir with layers of blackcurrant, violet, and graphite. Silky tannins with remarkable length.",
      tastingNotes: { nose: "Blackcurrant, violets, graphite, cedar", palate: "Silky tannins, cassis, dark chocolate, minerals", finish: "Exceptionally long and refined" },
      imageUrl: "/wines/margaux.jpg",
    },
  },
  {
    id: "wine-002",
    status: "anchored",
    ownerId: "user-001",
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-06-15T10:00:00Z",
    anchoredAt: "2024-02-01T10:05:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Opus One 2018",
      producer: "Opus One Winery",
      region: "Napa Valley",
      country: "USA",
      vintage: 2018,
      varietal: "Cabernet Sauvignon Blend",
      type: "red",
      abv: 14.5,
      volume: "750ml",
      quantity: 3,
      condition: "pristine",
      storage: "professional",
      drinkingWindow: { from: 2023, to: 2045 },
      ratings: [{ critic: "Wine Spectator", score: 97, year: 2021 }],
      certifications: ["Napa Valley AVA"],
      currentValue: 2400,
      purchasePrice: 1800,
      description: "A harmonious blend that captures the essence of Napa Valley. Rich, concentrated, and elegant.",
      tastingNotes: { nose: "Dark fruit, mocha, vanilla, spice", palate: "Rich cassis, dark plum, fine-grained tannins", finish: "Long, velvety, and persistent" },
      imageUrl: "/wines/opus-one.jpg",
    },
  },
  {
    id: "wine-003",
    status: "listed",
    ownerId: "user-002",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-07-01T10:00:00Z",
    anchoredAt: "2024-01-15T10:05:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Dom Pérignon 2012",
      producer: "Moët & Chandon",
      region: "Champagne",
      country: "France",
      vintage: 2012,
      varietal: "Chardonnay / Pinot Noir",
      type: "sparkling",
      abv: 12.5,
      volume: "750ml",
      quantity: 12,
      condition: "pristine",
      storage: "bonded_warehouse",
      drinkingWindow: { from: 2022, to: 2040 },
      ratings: [{ critic: "Robert Parker", score: 96, year: 2020 }],
      certifications: ["AOC Champagne", "Prestige Cuvée"],
      currentValue: 1800,
      purchasePrice: 1400,
      description: "A vintage of exceptional precision with brilliant acidity and depth. Toasty brioche meets fresh citrus.",
      tastingNotes: { nose: "Brioche, citrus zest, white flowers, almond", palate: "Crisp acidity, Meyer lemon, mineral tension", finish: "Elegantly persistent with a chalky edge" },
      imageUrl: "/wines/dom-perignon.jpg",
    },
  },
  {
    id: "wine-004",
    status: "anchored",
    ownerId: "user-001",
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-06-20T10:00:00Z",
    anchoredAt: "2024-03-01T10:05:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Penfolds Grange 2017",
      producer: "Penfolds",
      region: "South Australia",
      country: "Australia",
      vintage: 2017,
      varietal: "Shiraz",
      type: "red",
      abv: 14.5,
      volume: "750ml",
      quantity: 2,
      condition: "excellent",
      storage: "professional",
      drinkingWindow: { from: 2027, to: 2060 },
      ratings: [{ critic: "James Halliday", score: 99, year: 2022 }],
      certifications: ["Barossa Valley", "Icon Wine"],
      currentValue: 3500,
      purchasePrice: 2800,
      description: "Australia's most celebrated wine. Dark, intense, and powerfully structured with extraordinary depth.",
      tastingNotes: { nose: "Dark plum, blackberry, chocolate, earth", palate: "Dense, concentrated, layered dark fruit", finish: "Massive and persistent with fine tannins" },
      imageUrl: "/wines/grange.jpg",
    },
  },
  {
    id: "wine-005",
    status: "anchored",
    ownerId: "user-003",
    createdAt: "2024-02-15T10:00:00Z",
    updatedAt: "2024-06-15T10:00:00Z",
    anchoredAt: "2024-02-15T10:05:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Sassicaia 2019",
      producer: "Tenuta San Guido",
      region: "Bolgheri, Tuscany",
      country: "Italy",
      vintage: 2019,
      varietal: "Cabernet Sauvignon / Cabernet Franc",
      type: "red",
      abv: 14.0,
      volume: "750ml",
      quantity: 6,
      condition: "pristine",
      storage: "professional",
      drinkingWindow: { from: 2024, to: 2050 },
      ratings: [{ critic: "Wine Advocate", score: 98, year: 2022 }],
      certifications: ["DOC Bolgheri Sassicaia"],
      currentValue: 1600,
      purchasePrice: 1100,
      description: "The original Super Tuscan. A wine of remarkable purity and Mediterranean elegance.",
      tastingNotes: { nose: "Blackcurrant, Mediterranean herbs, iron", palate: "Elegant, structured, dark berry, tobacco", finish: "Long, savoury, and beautifully balanced" },
      imageUrl: "/wines/sassicaia.jpg",
    },
  },
  {
    id: "wine-006",
    status: "listed",
    ownerId: "user-002",
    createdAt: "2024-04-01T10:00:00Z",
    updatedAt: "2024-07-10T10:00:00Z",
    anchoredAt: "2024-04-01T10:05:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Cloudy Bay Sauvignon Blanc 2023",
      producer: "Cloudy Bay",
      region: "Marlborough",
      country: "New Zealand",
      vintage: 2023,
      varietal: "Sauvignon Blanc",
      type: "white",
      abv: 13.0,
      volume: "750ml",
      quantity: 24,
      condition: "pristine",
      storage: "bonded_warehouse",
      drinkingWindow: { from: 2023, to: 2027 },
      ratings: [{ critic: "Decanter", score: 93, year: 2024 }],
      certifications: ["Marlborough GI", "Sustainable Winegrowing NZ"],
      currentValue: 180,
      purchasePrice: 140,
      description: "The benchmark New Zealand Sauvignon Blanc. Vibrant, aromatic, and impossibly fresh.",
      tastingNotes: { nose: "Passionfruit, lime, cut grass, jalapeño", palate: "Zesty, tropical fruit, herbaceous, mineral", finish: "Crisp and refreshingly long" },
      imageUrl: "/wines/cloudy-bay.jpg",
    },
  },
  {
    id: "wine-007",
    status: "minted",
    ownerId: "user-001",
    createdAt: "2024-05-01T10:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Château d'Yquem 2016",
      producer: "Château d'Yquem",
      region: "Sauternes, Bordeaux",
      country: "France",
      vintage: 2016,
      varietal: "Sémillon / Sauvignon Blanc",
      type: "dessert",
      abv: 14.0,
      volume: "750ml",
      quantity: 3,
      condition: "pristine",
      storage: "professional",
      drinkingWindow: { from: 2025, to: 2080 },
      ratings: [{ critic: "Robert Parker", score: 98, year: 2019 }],
      certifications: ["AOC Sauternes", "Premier Cru Supérieur"],
      currentValue: 2200,
      purchasePrice: 1800,
      description: "The pinnacle of sweet white wine. Opulent, complex, and breathtakingly concentrated.",
      tastingNotes: { nose: "Apricot, saffron, honey, botrytis", palate: "Luscious, perfectly balanced acidity, peach", finish: "Endlessly complex and eternal" },
      imageUrl: "/wines/yquem.jpg",
    },
  },
  {
    id: "wine-008",
    status: "anchored",
    ownerId: "user-003",
    createdAt: "2024-03-15T10:00:00Z",
    updatedAt: "2024-06-20T10:00:00Z",
    anchoredAt: "2024-03-15T10:05:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Vega Sicilia Único 2013",
      producer: "Vega Sicilia",
      region: "Ribera del Duero",
      country: "Spain",
      vintage: 2013,
      varietal: "Tempranillo / Cabernet Sauvignon",
      type: "red",
      abv: 14.0,
      volume: "750ml",
      quantity: 4,
      condition: "pristine",
      storage: "professional",
      drinkingWindow: { from: 2025, to: 2055 },
      ratings: [{ critic: "Robert Parker", score: 97, year: 2021 }],
      certifications: ["DO Ribera del Duero"],
      currentValue: 2800,
      purchasePrice: 2100,
      description: "Spain's most iconic wine. A masterpiece of patience and tradition, aged for a decade before release.",
      tastingNotes: { nose: "Dark cherry, leather, tobacco, earth", palate: "Complex, layered, perfectly integrated", finish: "Extraordinarily long and aristocratic" },
      imageUrl: "/wines/vega-sicilia.jpg",
    },
  },
  {
    id: "wine-009",
    status: "anchored",
    ownerId: "user-001",
    createdAt: "2024-04-15T10:00:00Z",
    updatedAt: "2024-07-01T10:00:00Z",
    anchoredAt: "2024-04-15T10:05:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Krug Grande Cuvée 171ème Édition",
      producer: "Krug",
      region: "Champagne",
      country: "France",
      vintage: 2015,
      varietal: "Chardonnay / Pinot Noir / Pinot Meunier",
      type: "sparkling",
      abv: 12.5,
      volume: "750ml",
      quantity: 6,
      condition: "pristine",
      storage: "bonded_warehouse",
      drinkingWindow: { from: 2022, to: 2040 },
      ratings: [{ critic: "Wine Spectator", score: 96, year: 2022 }],
      certifications: ["AOC Champagne", "Grande Maison"],
      currentValue: 1400,
      purchasePrice: 1100,
      description: "A symphony of 127 wines from 12 vintages. Unparalleled complexity and generosity.",
      tastingNotes: { nose: "Toasted hazelnut, brioche, dried fruit, honey", palate: "Rich, full-bodied, layered complexity", finish: "Incredibly long with a saline freshness" },
      imageUrl: "/wines/krug.jpg",
    },
  },
  {
    id: "wine-010",
    status: "sold",
    ownerId: "user-004",
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-08-01T10:00:00Z",
    anchoredAt: "2024-01-20T10:05:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Whispering Angel Rosé 2023",
      producer: "Château d'Esclans",
      region: "Côtes de Provence",
      country: "France",
      vintage: 2023,
      varietal: "Grenache / Cinsault / Rolle",
      type: "rosé",
      abv: 13.0,
      volume: "750ml",
      quantity: 48,
      condition: "pristine",
      storage: "bonded_warehouse",
      drinkingWindow: { from: 2023, to: 2025 },
      ratings: [{ critic: "Decanter", score: 91, year: 2024 }],
      certifications: ["AOP Côtes de Provence"],
      currentValue: 120,
      purchasePrice: 95,
      description: "The world's most famous rosé. Pale, delicate, and effortlessly elegant.",
      tastingNotes: { nose: "Strawberry, white peach, rose petal", palate: "Delicate, fresh, mineral-driven", finish: "Clean and refreshing" },
      imageUrl: "/wines/whispering-angel.jpg",
    },
  },
  {
    id: "wine-011",
    status: "anchored",
    ownerId: "user-002",
    createdAt: "2024-05-15T10:00:00Z",
    updatedAt: "2024-07-15T10:00:00Z",
    anchoredAt: "2024-05-15T10:05:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Taylor's Vintage Port 2017",
      producer: "Taylor's Port",
      region: "Douro Valley",
      country: "Portugal",
      vintage: 2017,
      varietal: "Touriga Nacional / Touriga Franca",
      type: "fortified",
      abv: 20.0,
      volume: "750ml",
      quantity: 6,
      condition: "pristine",
      storage: "professional",
      drinkingWindow: { from: 2030, to: 2070 },
      ratings: [{ critic: "Wine Advocate", score: 97, year: 2019 }],
      certifications: ["DOC Douro", "Declared Vintage"],
      currentValue: 650,
      purchasePrice: 480,
      description: "A classic declared vintage from one of Port's greatest houses. Immensely concentrated and built for decades.",
      tastingNotes: { nose: "Blackberry, violet, slate, dark chocolate", palate: "Immense concentration, sweet fruit, firm structure", finish: "Massive, tannic, and endlessly long" },
      imageUrl: "/wines/taylors.jpg",
    },
  },
  {
    id: "wine-012",
    status: "anchored",
    ownerId: "user-001",
    createdAt: "2024-06-01T10:00:00Z",
    updatedAt: "2024-07-20T10:00:00Z",
    anchoredAt: "2024-06-01T10:05:00Z",
    faces: [],
    provenance: [],
    wineData: {
      name: "Leeuwin Estate Art Series Chardonnay 2020",
      producer: "Leeuwin Estate",
      region: "Margaret River",
      country: "Australia",
      vintage: 2020,
      varietal: "Chardonnay",
      type: "white",
      abv: 13.5,
      volume: "750ml",
      quantity: 6,
      condition: "pristine",
      storage: "professional",
      drinkingWindow: { from: 2023, to: 2035 },
      ratings: [{ critic: "James Halliday", score: 97, year: 2023 }],
      certifications: ["Margaret River GI"],
      currentValue: 550,
      purchasePrice: 420,
      description: "Australia's greatest Chardonnay. Power and finesse in perfect harmony.",
      tastingNotes: { nose: "White peach, cashew, fig, subtle oak", palate: "Concentrated, creamy, stone fruit, mineral", finish: "Incredibly long and harmonious" },
      imageUrl: "/wines/leeuwin.jpg",
    },
  },
];

// Add provenance to each wine
DEMO_WINES.forEach((wine) => {
  wine.provenance = makeProvenance(wine.id, wine.wineData.vintage);
});

export const DEMO_ACTIONS: Action[] = [
  {
    id: "act-001",
    wineId: "wine-001",
    type: "MINT",
    status: "completed",
    params: {},
    initiatedBy: "user-001",
    createdAt: "2024-01-10T10:00:00Z",
    completedAt: "2024-01-10T10:05:00Z",
  },
  {
    id: "act-002",
    wineId: "wine-003",
    type: "LIST",
    status: "completed",
    params: { price: 1800 },
    initiatedBy: "user-002",
    createdAt: "2024-07-01T10:00:00Z",
    completedAt: "2024-07-01T10:01:00Z",
  },
  {
    id: "act-003",
    wineId: "wine-010",
    type: "PURCHASE",
    status: "completed",
    params: { price: 120, buyer: "user-004" },
    initiatedBy: "user-004",
    createdAt: "2024-08-01T10:00:00Z",
    completedAt: "2024-08-01T10:02:00Z",
  },
  {
    id: "act-004",
    wineId: "wine-004",
    type: "VERIFY",
    status: "completed",
    params: {},
    result: { verified: true, verifier: "Langton's Authentication" },
    initiatedBy: "user-001",
    createdAt: "2024-06-20T10:00:00Z",
    completedAt: "2024-06-20T10:03:00Z",
  },
  {
    id: "act-005",
    wineId: "wine-001",
    type: "UPDATE_VALUATION",
    status: "completed",
    params: { newValue: 4800, previousValue: 3800, source: "Liv-ex" },
    initiatedBy: "system",
    createdAt: "2024-06-15T10:00:00Z",
    completedAt: "2024-06-15T10:00:30Z",
  },
  {
    id: "act-006",
    wineId: "wine-006",
    type: "LIST",
    status: "completed",
    params: { price: 180 },
    initiatedBy: "user-002",
    createdAt: "2024-07-10T10:00:00Z",
    completedAt: "2024-07-10T10:01:00Z",
  },
];

export const DEMO_STATS: DashboardStats = {
  totalWines: 12,
  totalValue: 22020,
  totalActions: 6,
  mintedThisMonth: 2,
  activeListings: 2,
  recentSales: 1,
  topRegions: [
    { region: "Bordeaux", count: 3 },
    { region: "Champagne", count: 2 },
    { region: "Australia", count: 2 },
    { region: "Tuscany", count: 1 },
    { region: "Napa Valley", count: 1 },
  ],
  valueByType: [
    { type: "red", value: 15100 },
    { type: "sparkling", value: 3200 },
    { type: "dessert", value: 2200 },
    { type: "fortified", value: 650 },
    { type: "white", value: 730 },
    { type: "rosé", value: 120 },
  ],
};
